version: '3.8'

services:
  client:
    build: 
      context: ./Client
    ports:
      - "5173:5173"
    volumes:
      - ./Client:/app
      - /app/node_modules
    env_file:
      - ./Client/.env  
    networks:
      - chat-mania-network
    depends_on:
      - server

  server:
    build: 
      context: ./Server
    ports:
      - "8747:8747"
    volumes:
      - ./Server:/app
      - /app/node_modules
    env_file:
      - ./Server/.env
    networks:
      - chat-mania-network

networks:
  chat-mania-network: